apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: 05-03-a
  labels:
    istio-injection: enabled
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service3
    version: v1
  name: service3-v1
  namespace: 05-03-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service3
        version: v1
    spec:
      containers:
      - image: wnyao/test-api:v1
        name: service3
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service3
  name: service3-v2
  namespace: 05-03-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
      version: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service3
        version: v2
    spec:
      containers:
      - image: wnyao/test-api:v2
        name: service3
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: service3
  namespace: 05-03-a
  labels:
    app: service3
    service: service3
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: service3

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: service3-gateway
  namespace: 05-03-a
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service3
  namespace: 05-03-a
spec:
  hosts:
  - "*"
  gateways:
  - service3-gateway
  http:
  - route:
    - destination:
        host: service3
        subset: v1
      weight: 50
    - destination:
        host: service3
        subset: v2
      weight: 50

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service3-destinationrule
  namespace: 05-03-a
spec:
  host: service3
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
