apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test
  labels:
    istio-injection: enabled
spec: {}
status: {}

---

apiVersion: v1
data:
  URL: istio-ingressgateway
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test-api-configmap
  namespace: test
