apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: 05-02-a
  labels:
    istio-injection: enabled
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: 05-02-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - image: wnyao/test-api:v1
        imagePullPolicy: IfNotPresent
        name: service1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: 05-02-a
  labels:
    app: service1
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: service1

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: service1-gateway
  namespace: 05-02-a
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "service1.gel.cyder.com.sg"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service1
  namespace: 05-02-a
spec:
  hosts:
  - "service1.gel.cyder.com.sg"
  gateways:
  - service1-gateway
  http:
  - route:
    - destination:
        port:
          number: 3000
        host: service1
      weight: 100

