apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hellocron
  namespace: test
spec:
  schedule: "* * * * *" 
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hellocron
            image: busybox
            args:
            - /bin/cat
            - /etc/os
          restartPolicy: Never
      backoffLimit: 3
  successfulJobsHistoryLimit: 3
  suspend: false
