apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: 05-04
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "kiali.gel.cyder.com.sg"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-virtualservice
  namespace: 05-04
spec:
  hosts:
  - "kiali.gel.cyder.com.sg"
  gateways:
  - kiali-gateway
  http:
  - route:
    - destination:
        host: kiali
        port:
          number: 20001

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali-detinationrule
  namespace: 05-04
spec:
  host: kiali
  trafficPolicy:
    tls:
      mode: DISABLE

