apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tracing-gateway
  namespace: 05-04
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "tracing.gel.cyder.com.sg"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing-virtualservice
  namespace: 05-04
spec:
  hosts:
  - "tracing.gel.cyder.com.sg"
  gateways:
  - tracing-gateway
  http:
  - route:
    - destination:
        host: tracing
        port:
          number: 80

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tracing-detinationrule
  namespace: 05-04
spec:
  host: tracing
  trafficPolicy:
    tls:
      mode: DISABLE

---
