apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-api
  name: test-api
  namespace: test
spec:
  ports:
  - port: 3000
    name: http
  type: NodePort
  selector:
    app: test-api
