apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: enabled
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - image: wnyao/test-api:v1
        imagePullPolicy: Always
        name: service1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: test
  labels:
    app: service1
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: service1

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
  namespace: test
spec:
  rules:
  - host: service.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: service1
          servicePort: 80
