{
 "title": "Istio Routing Requests",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Failed Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "istio_requests_total{response_code!=\"200\", request_protocol!=\"grpc\"}",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Total Successful Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "istio_requests_total{response_code=\"200\", request_protocol!=\"grpc\"}",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Failure routing of service3-malaysia",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "istio_requests_total{destination_service_name=\"service3-malaysia\", response_code!=\"200\"}",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Failure routing of service3-singapore",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "istio_requests_total{destination_service_name=\"service3-singapore\", response_code!=\"200\"}",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  }
 ]
}